### PR TITLE
adding unit tests

### PR DESCRIPTION
**Pull request by semmons99**

### CODE REVIEW

**Comment by jordanbyron** [comment]
:heart:  Yay tests   :heart:

Thanks @semmons99

**Comment by semmons99** [comment]
@jordanbyron now I just need to figure out how to test the actual bot without a ridiculous amount of mocking.

**Comment by semmons99** [comment]
@jordanbyron see anything here that's like **"WTF?! Seriously why'd he do that whack shit?"**

**Comment by jordanbyron** [comment]
@semmons99 nothing is really jumping out, besides rspec :trollface:

**Pull request merged**
